server {
    listen 80;
    server_name blog.golfspace.jp;
    client_max_body_size 500m;

    location / {
        root /usr/share/nginx/html;
        index blog.html;
        try_files $uri /blog.html;
    }

    location /api/blog/ {
        proxy_pass http://localhost:8001/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_read_timeout 300s;
        proxy_send_timeout 300s;
        client_max_body_size 500m;
    }
}
